### ISSUE TITLE
No Codec found

### ISSUE THREAD

**Issue by Yaksinikos** [nwgat/openshot-presets#1]
Hi,
I just installed, want to export a Video,but there came up this error:
[Error](http://openshot.org/files/libopenshot/classopenshot_1_1InvalidCodec.html)
How to fix it?
(I haven't installed any codec)
Linux Mint

**Comment by nwgat** [comment]
what did you try to export? h264? h265?

**Comment by Yaksinikos** [comment]
vp9/flac

**Comment by nwgat** [comment]
i think i fixed it now, can you try now?
is openshot running better these days? been a crash fest on windows for me ;(

**Comment by nwgat** [comment]
btw these presets are work-in-progress, thanks for reporting the issue =)

**Comment by Yaksinikos** [comment]
vp8/opus -> export works, just can't play because "multimedia-plugin not found"

x264/opus -> exception class 'openshot.InvalidSampleRate'

vp9/opus, x265/opus, vp9/flac, vp9/opus, x265/flac, x265/opus -> exception class 'openshot.InvalidCodec'

But I got some news of my Synaptic
- there isn't vp9, just vp8 (libvpx1)
- there isn't libx264, just libx264-dev and libx265
- there isn't libopus, there is libopus0 and libopus-dev

...
What I want is to export in mkv + flac + vp9/x265

**Comment by nwgat** [comment]
i go after ffmpeg, do you have ffmpeg installed? do the default ones work?

**Comment by nwgat** [comment]
you can try update the profiles now, i modified some of the files to do 48khz on opus

**Comment by Yaksinikos** [comment]
Yes ffmpeg is installed.
The default export-variants works fine.

As soon I want to play the vp8-variant there come a pop-up: "audio/x-unknown decoder"
Edit: export as x264/opus works now too, but the same pop-up

*There are missing codes in my system i think...

**Comment by nwgat** [comment]
so you can export but not play them? hmm did you try mpv, vlc, ffplay, gnome-mplayer?
i dont know mint but i know its based on ubuntu

**Comment by Yaksinikos** [comment]
Yes, it's nearly the same.
I tried VLC, but it's because of that fact I haven't installed any codec of those profiles.
I will try to fix, today.

**Comment by nwgat** [comment]
`sudo add-apt-repository "deb http://ppa.launchpad.net/mc3man/mpv-tests/ubuntu trusty main"`
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ED8E640A`
`sudo apt-get update && sudo apt-get install mpv`
`mpv yourfile.mkv`

**Comment by Yaksinikos** [comment]
Okay
Now there are just vp9 and x265 codecs missing :laughing:.
It's a bit harder to get them, I've never "compiled" files.

Export in VP8, x264, OPUS and FLAC for Matroska (mkv) work fine now.
!**important**! Opus isn't playabe in "Totem" or "VLC" but in "MPV Media Player"!

**Comment by nwgat** [comment]
to play it totem or other gstreamer player try
`sudo apt-get install gstreamer0.10-plugins-base gstreamer0.10-plugins-ugly gstreamer0.10-plugins-bad`

just tested it in ubuntu

**Comment by Yaksinikos** [comment]
Yes it's working, ... had to read next time the readme :laughing:
